# Generated by Django 4.2.7 on 2025-10-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(verbose_name='Query Text')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('crop_type', models.CharField(blank=True, max_length=100, verbose_name='Crop Type')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('response', models.TextField(verbose_name='AI Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Agricultural Query',
                'verbose_name_plural': 'Agricultural Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100, verbose_name='Crop Name')),
                ('season', models.CharField(max_length=50, verbose_name='Season')),
                ('advice_text', models.TextField(verbose_name='Advice Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Crop Advice',
                'verbose_name_plural': 'Crop Advice',
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('humidity', models.FloatField(verbose_name='Humidity')),
                ('rainfall', models.FloatField(verbose_name='Rainfall')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Data',
            },
        ),
    ]
