# Generated by Django 4.2.7 on 2025-10-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('resource_type', models.CharField(choices=[('guide', 'Farming Guide'), ('video', 'Video Tutorial'), ('article', 'Article'), ('tool', 'Tool/Resource'), ('research', 'Research Paper')], max_length=20, verbose_name='Type')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, verbose_name='Tags')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('alert_type', models.CharField(choices=[('frost', 'Frost Warning'), ('heat', 'Heat Wave'), ('drought', 'Drought'), ('flood', 'Flood Risk'), ('storm', 'Storm Warning'), ('pest', 'Pest Alert')], max_length=20, verbose_name='Alert Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, verbose_name='Severity')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Weather Alert',
                'verbose_name_plural': 'Weather Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=100, verbose_name='Commodity')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='Unit')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Currency')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
            ],
            options={
                'verbose_name': 'Market Price',
                'verbose_name_plural': 'Market Prices',
                'ordering': ['-recorded_at'],
                'unique_together': {('commodity', 'location', 'recorded_at')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=255, verbose_name='Session ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Custom Title')),
                ('notes', models.TextField(blank=True, verbose_name='Personal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor_app.agriculturalquery')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'unique_together': {('user_session', 'query')},
            },
        ),
    ]
